CREATE WAREHOUSE IF NOT EXISTS {{WAREHOUSE}} WAREHOUSE_SIZE='X-SMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE DATABASE IF NOT EXISTS {{DATABASE}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.BRONZE;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.SILVER;
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.GOLD;
CREATE OR REPLACE FILE FORMAT {{DATABASE}}.BRONZE.CSV_FORMAT TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 NULL_IF=('NULL','null','');
CREATE STAGE IF NOT EXISTS {{DATABASE}}.BRONZE.CSV_STAGE FILE_FORMAT={{DATABASE}}.BRONZE.CSV_FORMAT;
