CREATE TABLE IF NOT EXISTS {{DATABASE}}.BRONZE.CUSTOMERS (CUSTOMER_ID INTEGER,FIRST_NAME VARCHAR,LAST_NAME VARCHAR,EMAIL VARCHAR,SIGNUP_DATE DATE,COUNTRY VARCHAR);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.BRONZE.PRODUCTS (PRODUCT_ID INTEGER,PRODUCT_NAME VARCHAR,CATEGORY VARCHAR,PRICE NUMBER(10,2),ACTIVE BOOLEAN);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.BRONZE.ORDERS (ORDER_ID INTEGER,CUSTOMER_ID INTEGER,ORDER_DATE DATE,STATUS VARCHAR);
CREATE TABLE IF NOT EXISTS {{DATABASE}}.BRONZE.SALES (SALE_ID INTEGER,ORDER_ID INTEGER,PRODUCT_ID INTEGER,QUANTITY INTEGER,UNIT_PRICE NUMBER(10,2),DISCOUNT NUMBER(5,2),TOTAL_AMOUNT NUMBER(12,2));
