TRUNCATE TABLE {{DATABASE}}.BRONZE.CUSTOMERS;
TRUNCATE TABLE {{DATABASE}}.BRONZE.PRODUCTS;
TRUNCATE TABLE {{DATABASE}}.BRONZE.ORDERS;
TRUNCATE TABLE {{DATABASE}}.BRONZE.SALES;
COPY INTO {{DATABASE}}.BRONZE.CUSTOMERS FROM @{{DATABASE}}.BRONZE.CSV_STAGE/customers.csv FILE_FORMAT=(FORMAT_NAME={{DATABASE}}.BRONZE.CSV_FORMAT);
COPY INTO {{DATABASE}}.BRONZE.PRODUCTS FROM @{{DATABASE}}.BRONZE.CSV_STAGE/products.csv FILE_FORMAT=(FORMAT_NAME={{DATABASE}}.BRONZE.CSV_FORMAT);
COPY INTO {{DATABASE}}.BRONZE.ORDERS FROM @{{DATABASE}}.BRONZE.CSV_STAGE/orders.csv FILE_FORMAT=(FORMAT_NAME={{DATABASE}}.BRONZE.CSV_FORMAT);
COPY INTO {{DATABASE}}.BRONZE.SALES FROM @{{DATABASE}}.BRONZE.CSV_STAGE/sales.csv FILE_FORMAT=(FORMAT_NAME={{DATABASE}}.BRONZE.CSV_FORMAT);
