SELECT CUSTOMER_ID,COUNT(*) RECORD_COUNT FROM {{DATABASE}}.SILVER.CUSTOMERS GROUP BY CUSTOMER_ID HAVING COUNT(*)>1;
SELECT ORDER_ID,COUNT(*) RECORD_COUNT FROM {{DATABASE}}.SILVER.ORDERS GROUP BY ORDER_ID HAVING COUNT(*)>1;
SELECT O.ORDER_ID,O.CUSTOMER_ID FROM {{DATABASE}}.SILVER.ORDERS O LEFT JOIN {{DATABASE}}.SILVER.CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL;
SELECT S.SALE_ID,S.ORDER_ID FROM {{DATABASE}}.SILVER.SALES S LEFT JOIN {{DATABASE}}.SILVER.ORDERS O ON S.ORDER_ID=O.ORDER_ID WHERE O.ORDER_ID IS NULL;
SELECT S.SALE_ID,S.PRODUCT_ID FROM {{DATABASE}}.SILVER.SALES S LEFT JOIN {{DATABASE}}.SILVER.PRODUCTS P ON S.PRODUCT_ID=P.PRODUCT_ID WHERE P.PRODUCT_ID IS NULL;
SELECT * FROM {{DATABASE}}.SILVER.SALES WHERE QUANTITY<=0 OR UNIT_PRICE<0 OR DISCOUNT<0 OR DISCOUNT>1 OR TOTAL_AMOUNT<0;
SELECT SALE_ID,TOTAL_AMOUNT,CALCULATED_TOTAL,ABS(TOTAL_AMOUNT-CALCULATED_TOTAL) DIFFERENCE FROM {{DATABASE}}.SILVER.SALES WHERE ABS(TOTAL_AMOUNT-CALCULATED_TOTAL)>0.01;
