CREATE OR REPLACE DATABASE LENNAR_DEMO;

CREATE OR REPLACE SCHEMA LENNAR_DEMO.BRONZE;
CREATE OR REPLACE SCHEMA LENNAR_DEMO.SILVER;
CREATE OR REPLACE SCHEMA LENNAR_DEMO.GOLD;

CREATE OR REPLACE WAREHOUSE LENNAR_DEMO_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;
