USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

CREATE OR REPLACE TABLE BRONZE.CUSTOMERS (
    CUSTOMER_ID INTEGER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    SIGNUP_DATE DATE,
    COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE BRONZE.PRODUCTS (
    PRODUCT_ID INTEGER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2),
    ACTIVE BOOLEAN
);

CREATE OR REPLACE TABLE BRONZE.ORDERS (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    STATUS VARCHAR
);

CREATE OR REPLACE TABLE BRONZE.SALES (
    SALE_ID INTEGER,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(5,2),
    TOTAL_AMOUNT NUMBER(12,2)
);
