USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE CSV_STAGE
    FILE_FORMAT = CSV_FORMAT;

-- Upload the four files in /data to this stage, then verify:
LIST @LENNAR_DEMO.BRONZE.CSV_STAGE;
