USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

COPY INTO BRONZE.CUSTOMERS
FROM @BRONZE.CSV_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

COPY INTO BRONZE.PRODUCTS
FROM @BRONZE.CSV_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

COPY INTO BRONZE.ORDERS
FROM @BRONZE.CSV_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

COPY INTO BRONZE.SALES
FROM @BRONZE.CSV_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = BRONZE.CSV_FORMAT);

SELECT COUNT(*) AS CUSTOMER_COUNT FROM BRONZE.CUSTOMERS;
SELECT COUNT(*) AS PRODUCT_COUNT FROM BRONZE.PRODUCTS;
SELECT COUNT(*) AS ORDER_COUNT FROM BRONZE.ORDERS;
SELECT COUNT(*) AS SALES_COUNT FROM BRONZE.SALES;
