USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

CREATE OR REPLACE TABLE SILVER.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    SIGNUP_DATE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY
FROM BRONZE.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.PRODUCTS AS
SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    UPPER(TRIM(CATEGORY)) AS CATEGORY,
    PRICE,
    ACTIVE
FROM BRONZE.PRODUCTS
WHERE PRODUCT_ID IS NOT NULL
  AND PRICE >= 0;

CREATE OR REPLACE TABLE SILVER.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    UPPER(TRIM(STATUS)) AS STATUS
FROM BRONZE.ORDERS
WHERE ORDER_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE TABLE SILVER.SALES AS
SELECT
    SALE_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    TOTAL_AMOUNT,
    ROUND(QUANTITY * UNIT_PRICE * (1 - DISCOUNT), 2) AS CALCULATED_TOTAL
FROM BRONZE.SALES
WHERE SALE_ID IS NOT NULL
  AND QUANTITY > 0
  AND UNIT_PRICE >= 0;

SELECT * FROM SILVER.CUSTOMERS LIMIT 10;
SELECT * FROM SILVER.PRODUCTS LIMIT 10;
SELECT * FROM SILVER.ORDERS LIMIT 10;
SELECT * FROM SILVER.SALES LIMIT 10;
