USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

-- Duplicate customers
SELECT CUSTOMER_ID, COUNT(*) AS RECORD_COUNT
FROM SILVER.CUSTOMERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- Duplicate orders
SELECT ORDER_ID, COUNT(*) AS RECORD_COUNT
FROM SILVER.ORDERS
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

-- Orders without customers
SELECT O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE, O.STATUS
FROM SILVER.ORDERS O
LEFT JOIN SILVER.CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL;

-- Sales without orders
SELECT S.SALE_ID, S.ORDER_ID, S.PRODUCT_ID, S.TOTAL_AMOUNT
FROM SILVER.SALES S
LEFT JOIN SILVER.ORDERS O
    ON S.ORDER_ID = O.ORDER_ID
WHERE O.ORDER_ID IS NULL;

-- Sales without products
SELECT S.SALE_ID, S.PRODUCT_ID, S.ORDER_ID
FROM SILVER.SALES S
LEFT JOIN SILVER.PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

-- Invalid sales values
SELECT *
FROM SILVER.SALES
WHERE QUANTITY <= 0
   OR UNIT_PRICE < 0
   OR DISCOUNT < 0
   OR DISCOUNT > 1
   OR TOTAL_AMOUNT < 0;

-- Source total vs derived total
SELECT
    SALE_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    TOTAL_AMOUNT,
    CALCULATED_TOTAL,
    ABS(TOTAL_AMOUNT - CALCULATED_TOTAL) AS DIFFERENCE
FROM SILVER.SALES
WHERE ABS(TOTAL_AMOUNT - CALCULATED_TOTAL) > 0.01;

-- Profile order statuses
SELECT STATUS, COUNT(*) AS ORDER_COUNT
FROM SILVER.ORDERS
GROUP BY STATUS
ORDER BY STATUS;
