USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

CREATE OR REPLACE VIEW GOLD.ORDER_REVENUE AS
SELECT
    O.ORDER_ID,
    O.ORDER_DATE,
    O.STATUS,
    O.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.COUNTRY,
    SUM(S.TOTAL_AMOUNT) AS ORDER_REVENUE
FROM SILVER.ORDERS O
JOIN SILVER.CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN SILVER.SALES S
    ON O.ORDER_ID = S.ORDER_ID
GROUP BY
    O.ORDER_ID,
    O.ORDER_DATE,
    O.STATUS,
    O.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.COUNTRY;

CREATE OR REPLACE VIEW GOLD.PRODUCT_REVENUE AS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.ACTIVE,
    SUM(S.QUANTITY) AS UNITS_SOLD,
    SUM(S.TOTAL_AMOUNT) AS REVENUE
FROM SILVER.SALES S
JOIN SILVER.PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.ACTIVE;

CREATE OR REPLACE VIEW GOLD.CUSTOMER_REVENUE AS
SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL,
    C.COUNTRY,
    COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SILVER.CUSTOMERS C
JOIN SILVER.ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN SILVER.SALES S
    ON O.ORDER_ID = S.ORDER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL,
    C.COUNTRY;

CREATE OR REPLACE VIEW GOLD.MONTHLY_REVENUE AS
SELECT
    DATE_TRUNC('MONTH', O.ORDER_DATE) AS REVENUE_MONTH,
    COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SILVER.ORDERS O
JOIN SILVER.SALES S
    ON O.ORDER_ID = S.ORDER_ID
GROUP BY DATE_TRUNC('MONTH', O.ORDER_DATE);

SELECT * FROM GOLD.ORDER_REVENUE ORDER BY ORDER_REVENUE DESC LIMIT 20;
SELECT * FROM GOLD.PRODUCT_REVENUE ORDER BY REVENUE DESC LIMIT 20;
SELECT * FROM GOLD.CUSTOMER_REVENUE ORDER BY TOTAL_REVENUE DESC LIMIT 20;
SELECT * FROM GOLD.MONTHLY_REVENUE ORDER BY REVENUE_MONTH;
