USE WAREHOUSE LENNAR_DEMO_WH;
USE DATABASE LENNAR_DEMO;

CREATE OR REPLACE TABLE BRONZE.ORDER_UPDATES (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    STATUS VARCHAR
);

-- Update one existing order and add one new order.
INSERT INTO BRONZE.ORDER_UPDATES
VALUES
    (1000, 80, '2024-02-11', 'SHIPPED'),
    (9999, 1, CURRENT_DATE(), 'NEW');

SELECT *
FROM SILVER.ORDERS
WHERE ORDER_ID IN (1000, 9999);

MERGE INTO SILVER.ORDERS AS TARGET
USING BRONZE.ORDER_UPDATES AS SOURCE
    ON TARGET.ORDER_ID = SOURCE.ORDER_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.ORDER_DATE = SOURCE.ORDER_DATE,
        TARGET.STATUS = UPPER(TRIM(SOURCE.STATUS))

WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        STATUS
    )
    VALUES (
        SOURCE.ORDER_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.ORDER_DATE,
        UPPER(TRIM(SOURCE.STATUS))
    );

SELECT *
FROM SILVER.ORDERS
WHERE ORDER_ID IN (1000, 9999)
ORDER BY ORDER_ID;

-- Idempotency check after rerunning the MERGE.
SELECT ORDER_ID, COUNT(*) AS ROW_COUNT
FROM SILVER.ORDERS
WHERE ORDER_ID = 9999
GROUP BY ORDER_ID;
