USE WAREHOUSE LENNAR_DEMO_WH;

SHOW DATABASES LIKE 'LENNAR_DEMO';

CREATE OR REPLACE DATABASE LENNAR_DEMO_DEV
CLONE LENNAR_DEMO;

SHOW DATABASES LIKE 'LENNAR_DEMO_DEV';
SHOW SCHEMAS IN DATABASE LENNAR_DEMO_DEV;

SHOW TABLES IN SCHEMA LENNAR_DEMO_DEV.BRONZE;
SHOW TABLES IN SCHEMA LENNAR_DEMO_DEV.SILVER;
SHOW VIEWS IN SCHEMA LENNAR_DEMO_DEV.GOLD;

SELECT COUNT(*) AS DEV_ORDER_COUNT
FROM LENNAR_DEMO_DEV.SILVER.ORDERS;

SELECT COUNT(*) AS PROD_ORDER_COUNT
FROM LENNAR_DEMO.SILVER.ORDERS;

UPDATE LENNAR_DEMO_DEV.SILVER.ORDERS
SET STATUS = 'TEST_CLONE'
WHERE ORDER_ID = 1000;

SELECT *
FROM LENNAR_DEMO_DEV.SILVER.ORDERS
WHERE ORDER_ID = 1000;

SELECT *
FROM LENNAR_DEMO.SILVER.ORDERS
WHERE ORDER_ID = 1000;
